### 현재 비밀번호 검증
POST http://localhost:8080/api/users/me/password/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW5fdGVzdCIsImlhdCI6MTc2NzA3MDUyMCwiZXhwIjoxNzY3MDc0MTIwfQ.JABf7xKjNE4PwFAFXvOBDffxoxYxmrf77CWGP0mgjq4
Content-Type: application/json

{
  "password": "TestPassword123!"
}

### 비밀번호 변경
PUT http://localhost:8080/api/users/me/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW5fdGVzdCIsImlhdCI6MTc2NzA3MDUyMCwiZXhwIjoxNzY3MDc0MTIwfQ.JABf7xKjNE4PwFAFXvOBDffxoxYxmrf77CWGP0mgjq4
Content-Type: application/json

{
  "currentPassword": "TestPassword123!",
  "newPassword": "NewPassword123!"
}
