spring:
  application:
    name: playmate-backend
    

# spring-boot-stater-mail을 위한 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: gjwnsgud38@gmail.com
    password: kaymgcejwliebuzp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#output.ansi.enabled ???? ???? ???? ??
  output:
    ansi:
      enabled: always